### ISSUE TITLE
gspread.exceptions.SpreadsheetNotFound

### ISSUE THREAD

**Issue by chaiwebs** [manutorrente/SearchML#1]
![image](https://user-images.githubusercontent.com/59306343/89204955-4e5c5380-d58d-11ea-9f46-4acdeb0fb870.png)

I've followed all steps but keep getting "gspread.exceptions.SpreadsheetNotFound"

Any clue?

**Comment by manutorrente** [comment]
This means the code isn’t getting access to the sheets file properly. I can’t tell you exactly where the issue is, but it probably comes from not sharing the files or changing the names. 

If neither of these work, you should check the gspread documentation and find the mistake on your own.
https://gspread.readthedocs.io/en/latest/

**Comment by chaiwebs** [comment]
Finally got it working, it was the xlsx extension causing the trouble, created new files without it, and now works fine.

Thanks and keep up the good work!

**Comment by jaum20** [comment]
> Finally got it working, it was the xlsx extension causing the trouble, created new files without it, and now works fine.
> 
> Thanks and keep up the good work!

I'm also having this problem. Removed the extension but the problem persists

**Comment by manutorrente** [comment]
Have you shared the files with the service account?

**Comment by jaum20** [comment]
Yes. I had to create a new spreadsheet in my gdrive account and copy the content of your templates xlsx files in it to make it work
